#!/usr/bin/env python3
"""
Generate BRAM snap lookup table for Pythagorean triple angle snapping.

Maps angles 0..2π in 1024 steps to the nearest Pythagorean triple angle.
Output: Verilog $readmemh hex file + C header for ESP32.

Q4.12 fixed point: 4 integer bits (sign+3) + 12 fractional bits.
Range: -8.0 to +7.999755859375, resolution ~0.000244140625
Angle 0..2π ≈ 0..6.2832 fits in unsigned 0..25737 (Q4.12)
"""

import math
import sys

# ── Pythagorean triples (a, b, c) with primitive + selected non-primitive ──
TRIPLES = [
    (3, 4, 5),
    (5, 12, 13),
    (6, 8, 10),
    (7, 24, 25),
    (8, 15, 17),
    (9, 12, 15),
    (9, 40, 41),
    (10, 24, 26),
    (11, 60, 61),
    (12, 16, 20),
    (12, 35, 37),
    (13, 84, 85),
    (14, 48, 50),
    (15, 20, 25),
    (15, 36, 39),
    (15, 112, 113),
    (16, 30, 34),
    (16, 63, 65),
    (17, 144, 145),
    (18, 24, 30),
    (18, 80, 82),
    (19, 180, 181),
    (20, 21, 29),
    (20, 48, 52),
    (20, 99, 101),
    (21, 28, 35),
    (21, 72, 75),
    (24, 32, 40),
    (24, 45, 51),
    (24, 70, 74),
    (24, 143, 145),
    (25, 60, 65),
    (27, 36, 45),
    (28, 45, 53),
    (28, 96, 100),
    (30, 40, 50),
    (30, 72, 78),
    (32, 60, 68),
    (33, 44, 55),
    (33, 56, 65),
    (35, 84, 91),
    (36, 48, 60),
    (36, 77, 85),
    (39, 52, 65),
    (39, 80, 89),
    (40, 42, 58),
    (40, 75, 85),
    (42, 56, 70),
    (45, 60, 75),
    (48, 55, 73),
    (48, 64, 80),
    (51, 68, 85),
    (54, 72, 90),
    (57, 76, 95),
    (60, 63, 87),
    (60, 80, 100),
    (60, 91, 109),
    (63, 84, 105),
    (65, 72, 97),
    (66, 88, 110),
    (69, 92, 115),
    (72, 96, 120),
    (75, 100, 125),
    (80, 84, 116),
    (84, 112, 140),
]

# Build set of all triple angles (0..2π)
def build_angle_database():
    """Return list of (angle_rad, triple_a, triple_b, triple_c)."""
    angles = []
    for a, b, c in TRIPLES:
        # Four quadrants: (a,b), (b,a), (-a,b), (-b,a) → full circle
        theta = math.atan2(a, b)
        angles.append((theta, a, b, c))
        angles.append((math.atan2(b, a), b, a, c))
        angles.append((math.atan2(-a, b), -a, b, c))
        angles.append((math.atan2(-b, a), -b, a, c))
        # Also the negative-angle versions wrapped to 0..2π
        t = math.atan2(-a, -b)
        angles.append(((t + 2*math.pi) % (2*math.pi), a, b, c))
        t = math.atan2(-b, -a)
        angles.append(((t + 2*math.pi) % (2*math.pi), b, a, c))
        t = math.atan2(a, -b)
        angles.append(((t + 2*math.pi) % (2*math.pi), a, b, c))
        t = math.atan2(b, -a)
        angles.append(((t + 2*math.pi) % (2*math.pi), b, a, c))
    
    # Deduplicate by angle (keep closest triple)
    seen = {}
    for theta, a, b, c in angles:
        th = (theta + 2*math.pi) % (2*math.pi)
        if th not in seen or c < seen[th][1]:
            seen[th] = (th, c)
    
    return sorted(seen.values(), key=lambda x: x[0])

def q4_12_encode(value):
    """Encode a float to Q4.12 unsigned (for angles 0..2π)."""
    raw = int(round(value * 4096))
    return raw & 0xFFFF

def q4_12_decode(raw):
    """Decode Q4.12 unsigned back to float."""
    return raw / 4096.0

def generate_table(n_entries=1024):
    """Generate the snap LUT: list of (snapped_q4_12, triple_c, margin_q4_12)."""
    db = build_angle_database()
    db_angles = [entry[0] for entry in db]
    db_cs = [entry[1] for entry in db]
    
    table = []
    for i in range(n_entries):
        angle = (2 * math.pi * i) / n_entries
        
        # Find nearest triple angle (binary search)
        lo, hi = 0, len(db_angles) - 1
        while lo < hi:
            mid = (lo + hi) // 2
            if db_angles[mid] < angle:
                lo = mid + 1
            else:
                hi = mid
        
        # Check lo and lo-1
        best_idx = lo
        best_dist = abs(db_angles[lo] - angle)
        if lo > 0:
            d = abs(db_angles[lo-1] - angle)
            if d < best_dist:
                best_dist = d
                best_idx = lo - 1
        
        snapped_angle = db_angles[best_idx]
        triple_c = db_cs[best_idx]
        margin = best_dist
        
        table.append((
            q4_12_encode(snapped_angle),
            triple_c,
            q4_12_encode(margin * 4096)  # margin in Q4.12 (as fraction of full range)
        ))
    
    return table

def write_hex(table, outfile=sys.stdout):
    """Write $readmemh-compatible hex file.
    
    Each line: 32-bit word = {snapped[15:0], triple_c[15:0]}
    Margin is computed separately from the address delta.
    """
    print("// Snap LUT — 1024 entries × 32 bits", file=outfile)
    print("// Format: { snapped_angle_q4_12[15:0], triple_c[15:0] }", file=outfile)
    print("// Generated by generate_snap_table.py", file=outfile)
    print("//", file=outfile)
    
    for snapped, tc, margin in table:
        word = (snapped << 16) | (tc & 0xFFFF)
        print(f"{word:08X}", file=outfile)

def write_c_header(table, filename="snap_lut.h"):
    """Write C header for ESP32."""
    with open(filename, "w") as f:
        f.write("// Snap LUT — auto-generated by generate_snap_table.py\n")
        f.write("// 1024 entries × 32 bits: { snapped_angle_q4_12[15:0], triple_c[15:0] }\n")
        f.write("#ifndef SNAP_LUT_H\n")
        f.write("#define SNAP_LUT_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define SNAP_LUT_SIZE 1024\n\n")
        f.write("static const uint32_t snap_lut[SNAP_LUT_SIZE] = {\n")
        
        for i, (snapped, tc, margin) in enumerate(table):
            word = (snapped << 16) | (tc & 0xFFFF)
            comma = "," if i < len(table) - 1 else ""
            angle = (2 * math.pi * i) / len(table)
            f.write(f"    0x{word:08X}{comma}  // [{i:4d}] angle={angle:.4f} rad\n")
        
        f.write("};\n\n")
        
        # Also emit margin table (Q4.12)
        f.write("// Margin table: angular distance to nearest triple (Q4.12)\n")
        f.write("static const uint16_t snap_margin[SNAP_LUT_SIZE] = {\n")
        for i, (snapped, tc, margin) in enumerate(table):
            comma = "," if i < len(table) - 1 else ""
            f.write(f"    0x{margin:04X}{comma}\n")
        f.write("};\n\n")
        
        f.write("#endif // SNAP_LUT_H\n")

def write_margin_hex(table, filename="snap_margin.hex"):
    """Write separate margin hex file."""
    with open(filename, "w") as f:
        f.write("// Margin LUT — 1024 entries × 16 bits\n")
        f.write("// Angular distance to nearest triple (Q4.12 fixed point)\n")
        for snapped, tc, margin in table:
            f.write(f"{margin:04X}\n")

def write_addr_angle_map(filename="snap_addr_map.txt"):
    """Write a debug mapping of address → angle for verification."""
    with open(filename, "w") as f:
        for i in range(1024):
            angle = (2 * math.pi * i) / 1024
            f.write(f"{i:4d} -> {angle:.6f} rad ({math.degrees(angle):.2f} deg)\n")

if __name__ == "__main__":
    print("Generating snap LUT (1024 entries)...", file=sys.stderr)
    table = generate_table(1024)
    
    # Hex to stdout
    write_hex(table)
    
    # C header
    write_c_header(table, filename="/tmp/fpga-snap/snap_lut.h")
    
    # Margin hex
    write_margin_hex(table, filename="/tmp/fpga-snap/snap_margin.hex")
    
    # Debug map
    write_addr_angle_map(filename="/tmp/fpga-snap/snap_addr_map.txt")
    
    # Stats
    margins = [m for _, _, m in table]
    print(f"Done. Min margin: {min(margins)}, Max margin: {max(margins)}", file=sys.stderr)
    print(f"Files: snap_lut.hex (stdout), snap_lut.h, snap_margin.hex, snap_addr_map.txt", file=sys.stderr)
