// Snap LUT — auto-generated by generate_snap_table.py
// 1024 entries × 32 bits: { snapped_angle_q4_12[15:0], triple_c[15:0] }
#ifndef SNAP_LUT_H
#define SNAP_LUT_H

#include <stdint.h>

#define SNAP_LUT_SIZE 1024

static const uint32_t snap_lut[SNAP_LUT_SIZE] = {
    0x01AF00B5,  // [   0] angle=0.0000 rad
    0x01AF00B5,  // [   1] angle=0.0061 rad
    0x01AF00B5,  // [   2] angle=0.0123 rad
    0x01AF00B5,  // [   3] angle=0.0184 rad
    0x01AF00B5,  // [   4] angle=0.0245 rad
    0x01AF00B5,  // [   5] angle=0.0307 rad
    0x01AF00B5,  // [   6] angle=0.0368 rad
    0x01AF00B5,  // [   7] angle=0.0430 rad
    0x01AF00B5,  // [   8] angle=0.0491 rad
    0x01AF00B5,  // [   9] angle=0.0552 rad
    0x01AF00B5,  // [  10] angle=0.0614 rad
    0x01AF00B5,  // [  11] angle=0.0675 rad
    0x01AF00B5,  // [  12] angle=0.0736 rad
    0x01AF00B5,  // [  13] angle=0.0798 rad
    0x01AF00B5,  // [  14] angle=0.0859 rad
    0x01AF00B5,  // [  15] angle=0.0920 rad
    0x01AF00B5,  // [  16] angle=0.0982 rad
    0x01AF00B5,  // [  17] angle=0.1043 rad
    0x01AF00B5,  // [  18] angle=0.1104 rad
    0x01E10091,  // [  19] angle=0.1166 rad
    0x01E10091,  // [  20] angle=0.1227 rad
    0x02210071,  // [  21] angle=0.1289 rad
    0x02210071,  // [  22] angle=0.1350 rad
    0x02210071,  // [  23] angle=0.1411 rad
    0x02750055,  // [  24] angle=0.1473 rad
    0x02750055,  // [  25] angle=0.1534 rad
    0x02750055,  // [  26] angle=0.1595 rad
    0x02A90091,  // [  27] angle=0.1657 rad
    0x02A90091,  // [  28] angle=0.1718 rad
    0x02E7003D,  // [  29] angle=0.1779 rad
    0x02E7003D,  // [  30] angle=0.1841 rad
    0x02E7003D,  // [  31] angle=0.1902 rad
    0x03300065,  // [  32] angle=0.1963 rad
    0x03300065,  // [  33] angle=0.2025 rad
    0x03300065,  // [  34] angle=0.2086 rad
    0x038B0029,  // [  35] angle=0.2148 rad
    0x038B0029,  // [  36] angle=0.2209 rad
    0x038B0029,  // [  37] angle=0.2270 rad
    0x038B0029,  // [  38] angle=0.2332 rad
    0x03FB0041,  // [  39] angle=0.2393 rad
    0x03FB0041,  // [  40] angle=0.2454 rad
    0x03FB0041,  // [  41] angle=0.2516 rad
    0x03FB0041,  // [  42] angle=0.2577 rad
    0x03FB0041,  // [  43] angle=0.2638 rad
    0x048A0019,  // [  44] angle=0.2700 rad
    0x048A0019,  // [  45] angle=0.2761 rad
    0x048A0019,  // [  46] angle=0.2823 rad
    0x048A0019,  // [  47] angle=0.2884 rad
    0x048A0019,  // [  48] angle=0.2945 rad
    0x048A0019,  // [  49] angle=0.3007 rad
    0x048A0019,  // [  50] angle=0.3068 rad
    0x05490025,  // [  51] angle=0.3129 rad
    0x05490025,  // [  52] angle=0.3191 rad
    0x05490025,  // [  53] angle=0.3252 rad
    0x05490025,  // [  54] angle=0.3313 rad
    0x05490025,  // [  55] angle=0.3375 rad
    0x05490025,  // [  56] angle=0.3436 rad
    0x05490025,  // [  57] angle=0.3497 rad
    0x05490025,  // [  58] angle=0.3559 rad
    0x05490025,  // [  59] angle=0.3620 rad
    0x0651000D,  // [  60] angle=0.3682 rad
    0x0651000D,  // [  61] angle=0.3743 rad
    0x0651000D,  // [  62] angle=0.3804 rad
    0x0651000D,  // [  63] angle=0.3866 rad
    0x0651000D,  // [  64] angle=0.3927 rad
    0x0651000D,  // [  65] angle=0.3988 rad
    0x0651000D,  // [  66] angle=0.4050 rad
    0x0651000D,  // [  67] angle=0.4111 rad
    0x06FF0055,  // [  68] angle=0.4172 rad
    0x06FF0055,  // [  69] angle=0.4234 rad
    0x06FF0055,  // [  70] angle=0.4295 rad
    0x06FF0055,  // [  71] angle=0.4357 rad
    0x06FF0055,  // [  72] angle=0.4418 rad
    0x07420059,  // [  73] angle=0.4479 rad
    0x07420059,  // [  74] angle=0.4541 rad
    0x07420059,  // [  75] angle=0.4602 rad
    0x07420059,  // [  76] angle=0.4663 rad
    0x07D70011,  // [  77] angle=0.4725 rad
    0x07D70011,  // [  78] angle=0.4786 rad
    0x07D70011,  // [  79] angle=0.4847 rad
    0x07D70011,  // [  80] angle=0.4909 rad
    0x07D70011,  // [  81] angle=0.4970 rad
    0x07D70011,  // [  82] angle=0.5031 rad
    0x07D70011,  // [  83] angle=0.5093 rad
    0x08850041,  // [  84] angle=0.5154 rad
    0x08850041,  // [  85] angle=0.5216 rad
    0x08850041,  // [  86] angle=0.5277 rad
    0x08850041,  // [  87] angle=0.5338 rad
    0x08850041,  // [  88] angle=0.5400 rad
    0x08E80035,  // [  89] angle=0.5461 rad
    0x08E80035,  // [  90] angle=0.5522 rad
    0x08E80035,  // [  91] angle=0.5584 rad
    0x08E80035,  // [  92] angle=0.5645 rad
    0x0954006D,  // [  93] angle=0.5706 rad
    0x0954006D,  // [  94] angle=0.5768 rad
    0x0954006D,  // [  95] angle=0.5829 rad
    0x0954006D,  // [  96] angle=0.5890 rad
    0x0954006D,  // [  97] angle=0.5952 rad
    0x0954006D,  // [  98] angle=0.6013 rad
    0x0954006D,  // [  99] angle=0.6075 rad
    0x0A4C0005,  // [ 100] angle=0.6136 rad
    0x0A4C0005,  // [ 101] angle=0.6197 rad
    0x0A4C0005,  // [ 102] angle=0.6259 rad
    0x0A4C0005,  // [ 103] angle=0.6320 rad
    0x0A4C0005,  // [ 104] angle=0.6381 rad
    0x0A4C0005,  // [ 105] angle=0.6443 rad
    0x0A4C0005,  // [ 106] angle=0.6504 rad
    0x0A4C0005,  // [ 107] angle=0.6565 rad
    0x0A4C0005,  // [ 108] angle=0.6627 rad
    0x0A4C0005,  // [ 109] angle=0.6688 rad
    0x0A4C0005,  // [ 110] angle=0.6750 rad
    0x0B7B0049,  // [ 111] angle=0.6811 rad
    0x0B7B0049,  // [ 112] angle=0.6872 rad
    0x0B7B0049,  // [ 113] angle=0.6934 rad
    0x0B7B0049,  // [ 114] angle=0.6995 rad
    0x0B7B0049,  // [ 115] angle=0.7056 rad
    0x0B7B0049,  // [ 116] angle=0.7118 rad
    0x0B7B0049,  // [ 117] angle=0.7179 rad
    0x0B7B0049,  // [ 118] angle=0.7240 rad
    0x0BC00061,  // [ 119] angle=0.7302 rad
    0x0BC00061,  // [ 120] angle=0.7363 rad
    0x0BC00061,  // [ 121] angle=0.7424 rad
    0x0C2D001D,  // [ 122] angle=0.7486 rad
    0x0C2D001D,  // [ 123] angle=0.7547 rad
    0x0C2D001D,  // [ 124] angle=0.7609 rad
    0x0C2D001D,  // [ 125] angle=0.7670 rad
    0x0C2D001D,  // [ 126] angle=0.7731 rad
    0x0C2D001D,  // [ 127] angle=0.7793 rad
    0x0CF5001D,  // [ 128] angle=0.7854 rad
    0x0CF5001D,  // [ 129] angle=0.7915 rad
    0x0CF5001D,  // [ 130] angle=0.7977 rad
    0x0CF5001D,  // [ 131] angle=0.8038 rad
    0x0CF5001D,  // [ 132] angle=0.8099 rad
    0x0CF5001D,  // [ 133] angle=0.8161 rad
    0x0CF5001D,  // [ 134] angle=0.8222 rad
    0x0D620061,  // [ 135] angle=0.8283 rad
    0x0D620061,  // [ 136] angle=0.8345 rad
    0x0D620061,  // [ 137] angle=0.8406 rad
    0x0DA70049,  // [ 138] angle=0.8468 rad
    0x0DA70049,  // [ 139] angle=0.8529 rad
    0x0DA70049,  // [ 140] angle=0.8590 rad
    0x0DA70049,  // [ 141] angle=0.8652 rad
    0x0DA70049,  // [ 142] angle=0.8713 rad
    0x0DA70049,  // [ 143] angle=0.8774 rad
    0x0DA70049,  // [ 144] angle=0.8836 rad
    0x0DA70049,  // [ 145] angle=0.8897 rad
    0x0ED60005,  // [ 146] angle=0.8958 rad
    0x0ED60005,  // [ 147] angle=0.9020 rad
    0x0ED60005,  // [ 148] angle=0.9081 rad
    0x0ED60005,  // [ 149] angle=0.9143 rad
    0x0ED60005,  // [ 150] angle=0.9204 rad
    0x0ED60005,  // [ 151] angle=0.9265 rad
    0x0ED60005,  // [ 152] angle=0.9327 rad
    0x0ED60005,  // [ 153] angle=0.9388 rad
    0x0ED60005,  // [ 154] angle=0.9449 rad
    0x0ED60005,  // [ 155] angle=0.9511 rad
    0x0ED60005,  // [ 156] angle=0.9572 rad
    0x0FCE006D,  // [ 157] angle=0.9633 rad
    0x0FCE006D,  // [ 158] angle=0.9695 rad
    0x0FCE006D,  // [ 159] angle=0.9756 rad
    0x0FCE006D,  // [ 160] angle=0.9817 rad
    0x0FCE006D,  // [ 161] angle=0.9879 rad
    0x0FCE006D,  // [ 162] angle=0.9940 rad
    0x0FCE006D,  // [ 163] angle=1.0002 rad
    0x103A0035,  // [ 164] angle=1.0063 rad
    0x103A0035,  // [ 165] angle=1.0124 rad
    0x103A0035,  // [ 166] angle=1.0186 rad
    0x103A0035,  // [ 167] angle=1.0247 rad
    0x109D0041,  // [ 168] angle=1.0308 rad
    0x109D0041,  // [ 169] angle=1.0370 rad
    0x109D0041,  // [ 170] angle=1.0431 rad
    0x109D0041,  // [ 171] angle=1.0492 rad
    0x109D0041,  // [ 172] angle=1.0554 rad
    0x114B0011,  // [ 173] angle=1.0615 rad
    0x114B0011,  // [ 174] angle=1.0677 rad
    0x114B0011,  // [ 175] angle=1.0738 rad
    0x114B0011,  // [ 176] angle=1.0799 rad
    0x114B0011,  // [ 177] angle=1.0861 rad
    0x114B0011,  // [ 178] angle=1.0922 rad
    0x114B0011,  // [ 179] angle=1.0983 rad
    0x11E00059,  // [ 180] angle=1.1045 rad
    0x11E00059,  // [ 181] angle=1.1106 rad
    0x11E00059,  // [ 182] angle=1.1167 rad
    0x11E00059,  // [ 183] angle=1.1229 rad
    0x12230055,  // [ 184] angle=1.1290 rad
    0x12230055,  // [ 185] angle=1.1351 rad
    0x12230055,  // [ 186] angle=1.1413 rad
    0x12230055,  // [ 187] angle=1.1474 rad
    0x12230055,  // [ 188] angle=1.1536 rad
    0x12D1000D,  // [ 189] angle=1.1597 rad
    0x12D1000D,  // [ 190] angle=1.1658 rad
    0x12D1000D,  // [ 191] angle=1.1720 rad
    0x12D1000D,  // [ 192] angle=1.1781 rad
    0x12D1000D,  // [ 193] angle=1.1842 rad
    0x12D1000D,  // [ 194] angle=1.1904 rad
    0x12D1000D,  // [ 195] angle=1.1965 rad
    0x12D1000D,  // [ 196] angle=1.2026 rad
    0x13D90025,  // [ 197] angle=1.2088 rad
    0x13D90025,  // [ 198] angle=1.2149 rad
    0x13D90025,  // [ 199] angle=1.2210 rad
    0x13D90025,  // [ 200] angle=1.2272 rad
    0x13D90025,  // [ 201] angle=1.2333 rad
    0x13D90025,  // [ 202] angle=1.2395 rad
    0x13D90025,  // [ 203] angle=1.2456 rad
    0x13D90025,  // [ 204] angle=1.2517 rad
    0x13D90025,  // [ 205] angle=1.2579 rad
    0x14980019,  // [ 206] angle=1.2640 rad
    0x14980019,  // [ 207] angle=1.2701 rad
    0x14980019,  // [ 208] angle=1.2763 rad
    0x14980019,  // [ 209] angle=1.2824 rad
    0x14980019,  // [ 210] angle=1.2885 rad
    0x14980019,  // [ 211] angle=1.2947 rad
    0x14980019,  // [ 212] angle=1.3008 rad
    0x15270041,  // [ 213] angle=1.3070 rad
    0x15270041,  // [ 214] angle=1.3131 rad
    0x15270041,  // [ 215] angle=1.3192 rad
    0x15270041,  // [ 216] angle=1.3254 rad
    0x15270041,  // [ 217] angle=1.3315 rad
    0x15970029,  // [ 218] angle=1.3376 rad
    0x15970029,  // [ 219] angle=1.3438 rad
    0x15970029,  // [ 220] angle=1.3499 rad
    0x15970029,  // [ 221] angle=1.3560 rad
    0x15F10065,  // [ 222] angle=1.3622 rad
    0x15F10065,  // [ 223] angle=1.3683 rad
    0x15F10065,  // [ 224] angle=1.3744 rad
    0x163B003D,  // [ 225] angle=1.3806 rad
    0x163B003D,  // [ 226] angle=1.3867 rad
    0x163B003D,  // [ 227] angle=1.3929 rad
    0x16790091,  // [ 228] angle=1.3990 rad
    0x16790091,  // [ 229] angle=1.4051 rad
    0x16AD0055,  // [ 230] angle=1.4113 rad
    0x16AD0055,  // [ 231] angle=1.4174 rad
    0x16AD0055,  // [ 232] angle=1.4235 rad
    0x17010071,  // [ 233] angle=1.4297 rad
    0x17010071,  // [ 234] angle=1.4358 rad
    0x17010071,  // [ 235] angle=1.4419 rad
    0x17410091,  // [ 236] angle=1.4481 rad
    0x17410091,  // [ 237] angle=1.4542 rad
    0x177300B5,  // [ 238] angle=1.4603 rad
    0x177300B5,  // [ 239] angle=1.4665 rad
    0x177300B5,  // [ 240] angle=1.4726 rad
    0x177300B5,  // [ 241] angle=1.4788 rad
    0x177300B5,  // [ 242] angle=1.4849 rad
    0x177300B5,  // [ 243] angle=1.4910 rad
    0x177300B5,  // [ 244] angle=1.4972 rad
    0x177300B5,  // [ 245] angle=1.5033 rad
    0x177300B5,  // [ 246] angle=1.5094 rad
    0x177300B5,  // [ 247] angle=1.5156 rad
    0x177300B5,  // [ 248] angle=1.5217 rad
    0x177300B5,  // [ 249] angle=1.5278 rad
    0x177300B5,  // [ 250] angle=1.5340 rad
    0x177300B5,  // [ 251] angle=1.5401 rad
    0x177300B5,  // [ 252] angle=1.5463 rad
    0x177300B5,  // [ 253] angle=1.5524 rad
    0x177300B5,  // [ 254] angle=1.5585 rad
    0x177300B5,  // [ 255] angle=1.5647 rad
    0x1AD100B5,  // [ 256] angle=1.5708 rad
    0x1AD100B5,  // [ 257] angle=1.5769 rad
    0x1AD100B5,  // [ 258] angle=1.5831 rad
    0x1AD100B5,  // [ 259] angle=1.5892 rad
    0x1AD100B5,  // [ 260] angle=1.5953 rad
    0x1AD100B5,  // [ 261] angle=1.6015 rad
    0x1AD100B5,  // [ 262] angle=1.6076 rad
    0x1AD100B5,  // [ 263] angle=1.6137 rad
    0x1AD100B5,  // [ 264] angle=1.6199 rad
    0x1AD100B5,  // [ 265] angle=1.6260 rad
    0x1AD100B5,  // [ 266] angle=1.6322 rad
    0x1AD100B5,  // [ 267] angle=1.6383 rad
    0x1AD100B5,  // [ 268] angle=1.6444 rad
    0x1AD100B5,  // [ 269] angle=1.6506 rad
    0x1AD100B5,  // [ 270] angle=1.6567 rad
    0x1AD100B5,  // [ 271] angle=1.6628 rad
    0x1AD100B5,  // [ 272] angle=1.6690 rad
    0x1AD100B5,  // [ 273] angle=1.6751 rad
    0x1AD100B5,  // [ 274] angle=1.6812 rad
    0x1B030091,  // [ 275] angle=1.6874 rad
    0x1B030091,  // [ 276] angle=1.6935 rad
    0x1B430071,  // [ 277] angle=1.6997 rad
    0x1B430071,  // [ 278] angle=1.7058 rad
    0x1B430071,  // [ 279] angle=1.7119 rad
    0x1B970055,  // [ 280] angle=1.7181 rad
    0x1B970055,  // [ 281] angle=1.7242 rad
    0x1B970055,  // [ 282] angle=1.7303 rad
    0x1BCB0091,  // [ 283] angle=1.7365 rad
    0x1BCB0091,  // [ 284] angle=1.7426 rad
    0x1C09003D,  // [ 285] angle=1.7487 rad
    0x1C09003D,  // [ 286] angle=1.7549 rad
    0x1C09003D,  // [ 287] angle=1.7610 rad
    0x1C520065,  // [ 288] angle=1.7671 rad
    0x1C520065,  // [ 289] angle=1.7733 rad
    0x1C520065,  // [ 290] angle=1.7794 rad
    0x1CAC0029,  // [ 291] angle=1.7856 rad
    0x1CAC0029,  // [ 292] angle=1.7917 rad
    0x1CAC0029,  // [ 293] angle=1.7978 rad
    0x1CAC0029,  // [ 294] angle=1.8040 rad
    0x1D1D0041,  // [ 295] angle=1.8101 rad
    0x1D1D0041,  // [ 296] angle=1.8162 rad
    0x1D1D0041,  // [ 297] angle=1.8224 rad
    0x1D1D0041,  // [ 298] angle=1.8285 rad
    0x1D1D0041,  // [ 299] angle=1.8346 rad
    0x1DAC0019,  // [ 300] angle=1.8408 rad
    0x1DAC0019,  // [ 301] angle=1.8469 rad
    0x1DAC0019,  // [ 302] angle=1.8530 rad
    0x1DAC0019,  // [ 303] angle=1.8592 rad
    0x1DAC0019,  // [ 304] angle=1.8653 rad
    0x1DAC0019,  // [ 305] angle=1.8715 rad
    0x1DAC0019,  // [ 306] angle=1.8776 rad
    0x1E6B0025,  // [ 307] angle=1.8837 rad
    0x1E6B0025,  // [ 308] angle=1.8899 rad
    0x1E6B0025,  // [ 309] angle=1.8960 rad
    0x1E6B0025,  // [ 310] angle=1.9021 rad
    0x1E6B0025,  // [ 311] angle=1.9083 rad
    0x1E6B0025,  // [ 312] angle=1.9144 rad
    0x1E6B0025,  // [ 313] angle=1.9205 rad
    0x1E6B0025,  // [ 314] angle=1.9267 rad
    0x1E6B0025,  // [ 315] angle=1.9328 rad
    0x1F73000D,  // [ 316] angle=1.9390 rad
    0x1F73000D,  // [ 317] angle=1.9451 rad
    0x1F73000D,  // [ 318] angle=1.9512 rad
    0x1F73000D,  // [ 319] angle=1.9574 rad
    0x1F73000D,  // [ 320] angle=1.9635 rad
    0x1F73000D,  // [ 321] angle=1.9696 rad
    0x1F73000D,  // [ 322] angle=1.9758 rad
    0x1F73000D,  // [ 323] angle=1.9819 rad
    0x20210055,  // [ 324] angle=1.9880 rad
    0x20210055,  // [ 325] angle=1.9942 rad
    0x20210055,  // [ 326] angle=2.0003 rad
    0x20210055,  // [ 327] angle=2.0064 rad
    0x20210055,  // [ 328] angle=2.0126 rad
    0x20640059,  // [ 329] angle=2.0187 rad
    0x20640059,  // [ 330] angle=2.0249 rad
    0x20640059,  // [ 331] angle=2.0310 rad
    0x20640059,  // [ 332] angle=2.0371 rad
    0x20F90011,  // [ 333] angle=2.0433 rad
    0x20F90011,  // [ 334] angle=2.0494 rad
    0x20F90011,  // [ 335] angle=2.0555 rad
    0x20F90011,  // [ 336] angle=2.0617 rad
    0x20F90011,  // [ 337] angle=2.0678 rad
    0x20F90011,  // [ 338] angle=2.0739 rad
    0x20F90011,  // [ 339] angle=2.0801 rad
    0x21A70041,  // [ 340] angle=2.0862 rad
    0x21A70041,  // [ 341] angle=2.0923 rad
    0x21A70041,  // [ 342] angle=2.0985 rad
    0x21A70041,  // [ 343] angle=2.1046 rad
    0x21A70041,  // [ 344] angle=2.1108 rad
    0x220A0035,  // [ 345] angle=2.1169 rad
    0x220A0035,  // [ 346] angle=2.1230 rad
    0x220A0035,  // [ 347] angle=2.1292 rad
    0x220A0035,  // [ 348] angle=2.1353 rad
    0x2276006D,  // [ 349] angle=2.1414 rad
    0x2276006D,  // [ 350] angle=2.1476 rad
    0x2276006D,  // [ 351] angle=2.1537 rad
    0x2276006D,  // [ 352] angle=2.1598 rad
    0x2276006D,  // [ 353] angle=2.1660 rad
    0x2276006D,  // [ 354] angle=2.1721 rad
    0x2276006D,  // [ 355] angle=2.1783 rad
    0x236E0005,  // [ 356] angle=2.1844 rad
    0x236E0005,  // [ 357] angle=2.1905 rad
    0x236E0005,  // [ 358] angle=2.1967 rad
    0x236E0005,  // [ 359] angle=2.2028 rad
    0x236E0005,  // [ 360] angle=2.2089 rad
    0x236E0005,  // [ 361] angle=2.2151 rad
    0x236E0005,  // [ 362] angle=2.2212 rad
    0x236E0005,  // [ 363] angle=2.2273 rad
    0x236E0005,  // [ 364] angle=2.2335 rad
    0x236E0005,  // [ 365] angle=2.2396 rad
    0x236E0005,  // [ 366] angle=2.2457 rad
    0x249D0049,  // [ 367] angle=2.2519 rad
    0x249D0049,  // [ 368] angle=2.2580 rad
    0x249D0049,  // [ 369] angle=2.2642 rad
    0x249D0049,  // [ 370] angle=2.2703 rad
    0x249D0049,  // [ 371] angle=2.2764 rad
    0x249D0049,  // [ 372] angle=2.2826 rad
    0x249D0049,  // [ 373] angle=2.2887 rad
    0x249D0049,  // [ 374] angle=2.2948 rad
    0x24E20061,  // [ 375] angle=2.3010 rad
    0x24E20061,  // [ 376] angle=2.3071 rad
    0x24E20061,  // [ 377] angle=2.3132 rad
    0x254F001D,  // [ 378] angle=2.3194 rad
    0x254F001D,  // [ 379] angle=2.3255 rad
    0x254F001D,  // [ 380] angle=2.3317 rad
    0x254F001D,  // [ 381] angle=2.3378 rad
    0x254F001D,  // [ 382] angle=2.3439 rad
    0x254F001D,  // [ 383] angle=2.3501 rad
    0x2617001D,  // [ 384] angle=2.3562 rad
    0x2617001D,  // [ 385] angle=2.3623 rad
    0x2617001D,  // [ 386] angle=2.3685 rad
    0x2617001D,  // [ 387] angle=2.3746 rad
    0x2617001D,  // [ 388] angle=2.3807 rad
    0x2617001D,  // [ 389] angle=2.3869 rad
    0x2617001D,  // [ 390] angle=2.3930 rad
    0x26840061,  // [ 391] angle=2.3991 rad
    0x26840061,  // [ 392] angle=2.4053 rad
    0x26840061,  // [ 393] angle=2.4114 rad
    0x26C90049,  // [ 394] angle=2.4176 rad
    0x26C90049,  // [ 395] angle=2.4237 rad
    0x26C90049,  // [ 396] angle=2.4298 rad
    0x26C90049,  // [ 397] angle=2.4360 rad
    0x26C90049,  // [ 398] angle=2.4421 rad
    0x26C90049,  // [ 399] angle=2.4482 rad
    0x26C90049,  // [ 400] angle=2.4544 rad
    0x26C90049,  // [ 401] angle=2.4605 rad
    0x27F80005,  // [ 402] angle=2.4666 rad
    0x27F80005,  // [ 403] angle=2.4728 rad
    0x27F80005,  // [ 404] angle=2.4789 rad
    0x27F80005,  // [ 405] angle=2.4850 rad
    0x27F80005,  // [ 406] angle=2.4912 rad
    0x27F80005,  // [ 407] angle=2.4973 rad
    0x27F80005,  // [ 408] angle=2.5035 rad
    0x27F80005,  // [ 409] angle=2.5096 rad
    0x27F80005,  // [ 410] angle=2.5157 rad
    0x27F80005,  // [ 411] angle=2.5219 rad
    0x27F80005,  // [ 412] angle=2.5280 rad
    0x28F0006D,  // [ 413] angle=2.5341 rad
    0x28F0006D,  // [ 414] angle=2.5403 rad
    0x28F0006D,  // [ 415] angle=2.5464 rad
    0x28F0006D,  // [ 416] angle=2.5525 rad
    0x28F0006D,  // [ 417] angle=2.5587 rad
    0x28F0006D,  // [ 418] angle=2.5648 rad
    0x28F0006D,  // [ 419] angle=2.5710 rad
    0x295C0035,  // [ 420] angle=2.5771 rad
    0x295C0035,  // [ 421] angle=2.5832 rad
    0x295C0035,  // [ 422] angle=2.5894 rad
    0x295C0035,  // [ 423] angle=2.5955 rad
    0x29BF0041,  // [ 424] angle=2.6016 rad
    0x29BF0041,  // [ 425] angle=2.6078 rad
    0x29BF0041,  // [ 426] angle=2.6139 rad
    0x29BF0041,  // [ 427] angle=2.6200 rad
    0x29BF0041,  // [ 428] angle=2.6262 rad
    0x2A6D0011,  // [ 429] angle=2.6323 rad
    0x2A6D0011,  // [ 430] angle=2.6384 rad
    0x2A6D0011,  // [ 431] angle=2.6446 rad
    0x2A6D0011,  // [ 432] angle=2.6507 rad
    0x2A6D0011,  // [ 433] angle=2.6569 rad
    0x2A6D0011,  // [ 434] angle=2.6630 rad
    0x2A6D0011,  // [ 435] angle=2.6691 rad
    0x2B020059,  // [ 436] angle=2.6753 rad
    0x2B020059,  // [ 437] angle=2.6814 rad
    0x2B020059,  // [ 438] angle=2.6875 rad
    0x2B020059,  // [ 439] angle=2.6937 rad
    0x2B450055,  // [ 440] angle=2.6998 rad
    0x2B450055,  // [ 441] angle=2.7059 rad
    0x2B450055,  // [ 442] angle=2.7121 rad
    0x2B450055,  // [ 443] angle=2.7182 rad
    0x2B450055,  // [ 444] angle=2.7243 rad
    0x2BF3000D,  // [ 445] angle=2.7305 rad
    0x2BF3000D,  // [ 446] angle=2.7366 rad
    0x2BF3000D,  // [ 447] angle=2.7428 rad
    0x2BF3000D,  // [ 448] angle=2.7489 rad
    0x2BF3000D,  // [ 449] angle=2.7550 rad
    0x2BF3000D,  // [ 450] angle=2.7612 rad
    0x2BF3000D,  // [ 451] angle=2.7673 rad
    0x2BF3000D,  // [ 452] angle=2.7734 rad
    0x2CFB0025,  // [ 453] angle=2.7796 rad
    0x2CFB0025,  // [ 454] angle=2.7857 rad
    0x2CFB0025,  // [ 455] angle=2.7918 rad
    0x2CFB0025,  // [ 456] angle=2.7980 rad
    0x2CFB0025,  // [ 457] angle=2.8041 rad
    0x2CFB0025,  // [ 458] angle=2.8103 rad
    0x2CFB0025,  // [ 459] angle=2.8164 rad
    0x2CFB0025,  // [ 460] angle=2.8225 rad
    0x2CFB0025,  // [ 461] angle=2.8287 rad
    0x2DBA0019,  // [ 462] angle=2.8348 rad
    0x2DBA0019,  // [ 463] angle=2.8409 rad
    0x2DBA0019,  // [ 464] angle=2.8471 rad
    0x2DBA0019,  // [ 465] angle=2.8532 rad
    0x2DBA0019,  // [ 466] angle=2.8593 rad
    0x2DBA0019,  // [ 467] angle=2.8655 rad
    0x2DBA0019,  // [ 468] angle=2.8716 rad
    0x2E490041,  // [ 469] angle=2.8777 rad
    0x2E490041,  // [ 470] angle=2.8839 rad
    0x2E490041,  // [ 471] angle=2.8900 rad
    0x2E490041,  // [ 472] angle=2.8962 rad
    0x2E490041,  // [ 473] angle=2.9023 rad
    0x2EB90029,  // [ 474] angle=2.9084 rad
    0x2EB90029,  // [ 475] angle=2.9146 rad
    0x2EB90029,  // [ 476] angle=2.9207 rad
    0x2EB90029,  // [ 477] angle=2.9268 rad
    0x2F130065,  // [ 478] angle=2.9330 rad
    0x2F130065,  // [ 479] angle=2.9391 rad
    0x2F130065,  // [ 480] angle=2.9452 rad
    0x2F5D003D,  // [ 481] angle=2.9514 rad
    0x2F5D003D,  // [ 482] angle=2.9575 rad
    0x2F5D003D,  // [ 483] angle=2.9637 rad
    0x2F9B0091,  // [ 484] angle=2.9698 rad
    0x2F9B0091,  // [ 485] angle=2.9759 rad
    0x2FCF0055,  // [ 486] angle=2.9821 rad
    0x2FCF0055,  // [ 487] angle=2.9882 rad
    0x2FCF0055,  // [ 488] angle=2.9943 rad
    0x30230071,  // [ 489] angle=3.0005 rad
    0x30230071,  // [ 490] angle=3.0066 rad
    0x30230071,  // [ 491] angle=3.0127 rad
    0x30630091,  // [ 492] angle=3.0189 rad
    0x30630091,  // [ 493] angle=3.0250 rad
    0x309500B5,  // [ 494] angle=3.0311 rad
    0x309500B5,  // [ 495] angle=3.0373 rad
    0x309500B5,  // [ 496] angle=3.0434 rad
    0x309500B5,  // [ 497] angle=3.0496 rad
    0x309500B5,  // [ 498] angle=3.0557 rad
    0x309500B5,  // [ 499] angle=3.0618 rad
    0x309500B5,  // [ 500] angle=3.0680 rad
    0x309500B5,  // [ 501] angle=3.0741 rad
    0x309500B5,  // [ 502] angle=3.0802 rad
    0x309500B5,  // [ 503] angle=3.0864 rad
    0x309500B5,  // [ 504] angle=3.0925 rad
    0x309500B5,  // [ 505] angle=3.0986 rad
    0x309500B5,  // [ 506] angle=3.1048 rad
    0x309500B5,  // [ 507] angle=3.1109 rad
    0x309500B5,  // [ 508] angle=3.1170 rad
    0x309500B5,  // [ 509] angle=3.1232 rad
    0x309500B5,  // [ 510] angle=3.1293 rad
    0x309500B5,  // [ 511] angle=3.1355 rad
    0x33F300B5,  // [ 512] angle=3.1416 rad
    0x33F300B5,  // [ 513] angle=3.1477 rad
    0x33F300B5,  // [ 514] angle=3.1539 rad
    0x33F300B5,  // [ 515] angle=3.1600 rad
    0x33F300B5,  // [ 516] angle=3.1661 rad
    0x33F300B5,  // [ 517] angle=3.1723 rad
    0x33F300B5,  // [ 518] angle=3.1784 rad
    0x33F300B5,  // [ 519] angle=3.1845 rad
    0x33F300B5,  // [ 520] angle=3.1907 rad
    0x33F300B5,  // [ 521] angle=3.1968 rad
    0x33F300B5,  // [ 522] angle=3.2030 rad
    0x33F300B5,  // [ 523] angle=3.2091 rad
    0x33F300B5,  // [ 524] angle=3.2152 rad
    0x33F300B5,  // [ 525] angle=3.2214 rad
    0x33F300B5,  // [ 526] angle=3.2275 rad
    0x33F300B5,  // [ 527] angle=3.2336 rad
    0x33F300B5,  // [ 528] angle=3.2398 rad
    0x33F300B5,  // [ 529] angle=3.2459 rad
    0x33F300B5,  // [ 530] angle=3.2520 rad
    0x34250091,  // [ 531] angle=3.2582 rad
    0x34250091,  // [ 532] angle=3.2643 rad
    0x34650071,  // [ 533] angle=3.2704 rad
    0x34650071,  // [ 534] angle=3.2766 rad
    0x34650071,  // [ 535] angle=3.2827 rad
    0x34B90055,  // [ 536] angle=3.2889 rad
    0x34B90055,  // [ 537] angle=3.2950 rad
    0x34B90055,  // [ 538] angle=3.3011 rad
    0x34ED0091,  // [ 539] angle=3.3073 rad
    0x34ED0091,  // [ 540] angle=3.3134 rad
    0x352B003D,  // [ 541] angle=3.3195 rad
    0x352B003D,  // [ 542] angle=3.3257 rad
    0x352B003D,  // [ 543] angle=3.3318 rad
    0x35740065,  // [ 544] angle=3.3379 rad
    0x35740065,  // [ 545] angle=3.3441 rad
    0x35740065,  // [ 546] angle=3.3502 rad
    0x35CE0029,  // [ 547] angle=3.3563 rad
    0x35CE0029,  // [ 548] angle=3.3625 rad
    0x35CE0029,  // [ 549] angle=3.3686 rad
    0x35CE0029,  // [ 550] angle=3.3748 rad
    0x363F0041,  // [ 551] angle=3.3809 rad
    0x363F0041,  // [ 552] angle=3.3870 rad
    0x363F0041,  // [ 553] angle=3.3932 rad
    0x363F0041,  // [ 554] angle=3.3993 rad
    0x363F0041,  // [ 555] angle=3.4054 rad
    0x36CE0019,  // [ 556] angle=3.4116 rad
    0x36CE0019,  // [ 557] angle=3.4177 rad
    0x36CE0019,  // [ 558] angle=3.4238 rad
    0x36CE0019,  // [ 559] angle=3.4300 rad
    0x36CE0019,  // [ 560] angle=3.4361 rad
    0x36CE0019,  // [ 561] angle=3.4423 rad
    0x36CE0019,  // [ 562] angle=3.4484 rad
    0x378D0025,  // [ 563] angle=3.4545 rad
    0x378D0025,  // [ 564] angle=3.4607 rad
    0x378D0025,  // [ 565] angle=3.4668 rad
    0x378D0025,  // [ 566] angle=3.4729 rad
    0x378D0025,  // [ 567] angle=3.4791 rad
    0x378D0025,  // [ 568] angle=3.4852 rad
    0x378D0025,  // [ 569] angle=3.4913 rad
    0x378D0025,  // [ 570] angle=3.4975 rad
    0x378D0025,  // [ 571] angle=3.5036 rad
    0x3895000D,  // [ 572] angle=3.5097 rad
    0x3895000D,  // [ 573] angle=3.5159 rad
    0x3895000D,  // [ 574] angle=3.5220 rad
    0x3895000D,  // [ 575] angle=3.5282 rad
    0x3895000D,  // [ 576] angle=3.5343 rad
    0x3895000D,  // [ 577] angle=3.5404 rad
    0x3895000D,  // [ 578] angle=3.5466 rad
    0x3895000D,  // [ 579] angle=3.5527 rad
    0x39430055,  // [ 580] angle=3.5588 rad
    0x39430055,  // [ 581] angle=3.5650 rad
    0x39430055,  // [ 582] angle=3.5711 rad
    0x39430055,  // [ 583] angle=3.5772 rad
    0x39430055,  // [ 584] angle=3.5834 rad
    0x39860059,  // [ 585] angle=3.5895 rad
    0x39860059,  // [ 586] angle=3.5957 rad
    0x39860059,  // [ 587] angle=3.6018 rad
    0x39860059,  // [ 588] angle=3.6079 rad
    0x3A1B0011,  // [ 589] angle=3.6141 rad
    0x3A1B0011,  // [ 590] angle=3.6202 rad
    0x3A1B0011,  // [ 591] angle=3.6263 rad
    0x3A1B0011,  // [ 592] angle=3.6325 rad
    0x3A1B0011,  // [ 593] angle=3.6386 rad
    0x3A1B0011,  // [ 594] angle=3.6447 rad
    0x3A1B0011,  // [ 595] angle=3.6509 rad
    0x3AC90041,  // [ 596] angle=3.6570 rad
    0x3AC90041,  // [ 597] angle=3.6631 rad
    0x3AC90041,  // [ 598] angle=3.6693 rad
    0x3AC90041,  // [ 599] angle=3.6754 rad
    0x3AC90041,  // [ 600] angle=3.6816 rad
    0x3B2C0035,  // [ 601] angle=3.6877 rad
    0x3B2C0035,  // [ 602] angle=3.6938 rad
    0x3B2C0035,  // [ 603] angle=3.7000 rad
    0x3B2C0035,  // [ 604] angle=3.7061 rad
    0x3B98006D,  // [ 605] angle=3.7122 rad
    0x3B98006D,  // [ 606] angle=3.7184 rad
    0x3B98006D,  // [ 607] angle=3.7245 rad
    0x3B98006D,  // [ 608] angle=3.7306 rad
    0x3B98006D,  // [ 609] angle=3.7368 rad
    0x3B98006D,  // [ 610] angle=3.7429 rad
    0x3B98006D,  // [ 611] angle=3.7490 rad
    0x3C900005,  // [ 612] angle=3.7552 rad
    0x3C900005,  // [ 613] angle=3.7613 rad
    0x3C900005,  // [ 614] angle=3.7675 rad
    0x3C900005,  // [ 615] angle=3.7736 rad
    0x3C900005,  // [ 616] angle=3.7797 rad
    0x3C900005,  // [ 617] angle=3.7859 rad
    0x3C900005,  // [ 618] angle=3.7920 rad
    0x3C900005,  // [ 619] angle=3.7981 rad
    0x3C900005,  // [ 620] angle=3.8043 rad
    0x3C900005,  // [ 621] angle=3.8104 rad
    0x3C900005,  // [ 622] angle=3.8165 rad
    0x3DBF0049,  // [ 623] angle=3.8227 rad
    0x3DBF0049,  // [ 624] angle=3.8288 rad
    0x3DBF0049,  // [ 625] angle=3.8350 rad
    0x3DBF0049,  // [ 626] angle=3.8411 rad
    0x3DBF0049,  // [ 627] angle=3.8472 rad
    0x3DBF0049,  // [ 628] angle=3.8534 rad
    0x3DBF0049,  // [ 629] angle=3.8595 rad
    0x3DBF0049,  // [ 630] angle=3.8656 rad
    0x3E040061,  // [ 631] angle=3.8718 rad
    0x3E040061,  // [ 632] angle=3.8779 rad
    0x3E040061,  // [ 633] angle=3.8840 rad
    0x3E71001D,  // [ 634] angle=3.8902 rad
    0x3E71001D,  // [ 635] angle=3.8963 rad
    0x3E71001D,  // [ 636] angle=3.9024 rad
    0x3E71001D,  // [ 637] angle=3.9086 rad
    0x3E71001D,  // [ 638] angle=3.9147 rad
    0x3E71001D,  // [ 639] angle=3.9209 rad
    0x3F39001D,  // [ 640] angle=3.9270 rad
    0x3F39001D,  // [ 641] angle=3.9331 rad
    0x3F39001D,  // [ 642] angle=3.9393 rad
    0x3F39001D,  // [ 643] angle=3.9454 rad
    0x3F39001D,  // [ 644] angle=3.9515 rad
    0x3F39001D,  // [ 645] angle=3.9577 rad
    0x3F39001D,  // [ 646] angle=3.9638 rad
    0x3FA60061,  // [ 647] angle=3.9699 rad
    0x3FA60061,  // [ 648] angle=3.9761 rad
    0x3FA60061,  // [ 649] angle=3.9822 rad
    0x3FEB0049,  // [ 650] angle=3.9884 rad
    0x3FEB0049,  // [ 651] angle=3.9945 rad
    0x3FEB0049,  // [ 652] angle=4.0006 rad
    0x3FEB0049,  // [ 653] angle=4.0068 rad
    0x3FEB0049,  // [ 654] angle=4.0129 rad
    0x3FEB0049,  // [ 655] angle=4.0190 rad
    0x3FEB0049,  // [ 656] angle=4.0252 rad
    0x3FEB0049,  // [ 657] angle=4.0313 rad
    0x411A0005,  // [ 658] angle=4.0374 rad
    0x411A0005,  // [ 659] angle=4.0436 rad
    0x411A0005,  // [ 660] angle=4.0497 rad
    0x411A0005,  // [ 661] angle=4.0558 rad
    0x411A0005,  // [ 662] angle=4.0620 rad
    0x411A0005,  // [ 663] angle=4.0681 rad
    0x411A0005,  // [ 664] angle=4.0743 rad
    0x411A0005,  // [ 665] angle=4.0804 rad
    0x411A0005,  // [ 666] angle=4.0865 rad
    0x411A0005,  // [ 667] angle=4.0927 rad
    0x411A0005,  // [ 668] angle=4.0988 rad
    0x4212006D,  // [ 669] angle=4.1049 rad
    0x4212006D,  // [ 670] angle=4.1111 rad
    0x4212006D,  // [ 671] angle=4.1172 rad
    0x4212006D,  // [ 672] angle=4.1233 rad
    0x4212006D,  // [ 673] angle=4.1295 rad
    0x4212006D,  // [ 674] angle=4.1356 rad
    0x4212006D,  // [ 675] angle=4.1417 rad
    0x427E0035,  // [ 676] angle=4.1479 rad
    0x427E0035,  // [ 677] angle=4.1540 rad
    0x427E0035,  // [ 678] angle=4.1602 rad
    0x427E0035,  // [ 679] angle=4.1663 rad
    0x42E10041,  // [ 680] angle=4.1724 rad
    0x42E10041,  // [ 681] angle=4.1786 rad
    0x42E10041,  // [ 682] angle=4.1847 rad
    0x42E10041,  // [ 683] angle=4.1908 rad
    0x42E10041,  // [ 684] angle=4.1970 rad
    0x438F0011,  // [ 685] angle=4.2031 rad
    0x438F0011,  // [ 686] angle=4.2092 rad
    0x438F0011,  // [ 687] angle=4.2154 rad
    0x438F0011,  // [ 688] angle=4.2215 rad
    0x438F0011,  // [ 689] angle=4.2277 rad
    0x438F0011,  // [ 690] angle=4.2338 rad
    0x438F0011,  // [ 691] angle=4.2399 rad
    0x44240059,  // [ 692] angle=4.2461 rad
    0x44240059,  // [ 693] angle=4.2522 rad
    0x44240059,  // [ 694] angle=4.2583 rad
    0x44240059,  // [ 695] angle=4.2645 rad
    0x44670055,  // [ 696] angle=4.2706 rad
    0x44670055,  // [ 697] angle=4.2767 rad
    0x44670055,  // [ 698] angle=4.2829 rad
    0x44670055,  // [ 699] angle=4.2890 rad
    0x44670055,  // [ 700] angle=4.2951 rad
    0x4515000D,  // [ 701] angle=4.3013 rad
    0x4515000D,  // [ 702] angle=4.3074 rad
    0x4515000D,  // [ 703] angle=4.3136 rad
    0x4515000D,  // [ 704] angle=4.3197 rad
    0x4515000D,  // [ 705] angle=4.3258 rad
    0x4515000D,  // [ 706] angle=4.3320 rad
    0x4515000D,  // [ 707] angle=4.3381 rad
    0x4515000D,  // [ 708] angle=4.3442 rad
    0x461D0025,  // [ 709] angle=4.3504 rad
    0x461D0025,  // [ 710] angle=4.3565 rad
    0x461D0025,  // [ 711] angle=4.3626 rad
    0x461D0025,  // [ 712] angle=4.3688 rad
    0x461D0025,  // [ 713] angle=4.3749 rad
    0x461D0025,  // [ 714] angle=4.3810 rad
    0x461D0025,  // [ 715] angle=4.3872 rad
    0x461D0025,  // [ 716] angle=4.3933 rad
    0x461D0025,  // [ 717] angle=4.3995 rad
    0x46DC0019,  // [ 718] angle=4.4056 rad
    0x46DC0019,  // [ 719] angle=4.4117 rad
    0x46DC0019,  // [ 720] angle=4.4179 rad
    0x46DC0019,  // [ 721] angle=4.4240 rad
    0x46DC0019,  // [ 722] angle=4.4301 rad
    0x46DC0019,  // [ 723] angle=4.4363 rad
    0x46DC0019,  // [ 724] angle=4.4424 rad
    0x476B0041,  // [ 725] angle=4.4485 rad
    0x476B0041,  // [ 726] angle=4.4547 rad
    0x476B0041,  // [ 727] angle=4.4608 rad
    0x476B0041,  // [ 728] angle=4.4670 rad
    0x476B0041,  // [ 729] angle=4.4731 rad
    0x47DB0029,  // [ 730] angle=4.4792 rad
    0x47DB0029,  // [ 731] angle=4.4854 rad
    0x47DB0029,  // [ 732] angle=4.4915 rad
    0x47DB0029,  // [ 733] angle=4.4976 rad
    0x48350065,  // [ 734] angle=4.5038 rad
    0x48350065,  // [ 735] angle=4.5099 rad
    0x48350065,  // [ 736] angle=4.5160 rad
    0x487F003D,  // [ 737] angle=4.5222 rad
    0x487F003D,  // [ 738] angle=4.5283 rad
    0x487F003D,  // [ 739] angle=4.5344 rad
    0x48BD0091,  // [ 740] angle=4.5406 rad
    0x48BD0091,  // [ 741] angle=4.5467 rad
    0x48F10055,  // [ 742] angle=4.5529 rad
    0x48F10055,  // [ 743] angle=4.5590 rad
    0x48F10055,  // [ 744] angle=4.5651 rad
    0x49450071,  // [ 745] angle=4.5713 rad
    0x49450071,  // [ 746] angle=4.5774 rad
    0x49450071,  // [ 747] angle=4.5835 rad
    0x49850091,  // [ 748] angle=4.5897 rad
    0x49850091,  // [ 749] angle=4.5958 rad
    0x49B700B5,  // [ 750] angle=4.6019 rad
    0x49B700B5,  // [ 751] angle=4.6081 rad
    0x49B700B5,  // [ 752] angle=4.6142 rad
    0x49B700B5,  // [ 753] angle=4.6204 rad
    0x49B700B5,  // [ 754] angle=4.6265 rad
    0x49B700B5,  // [ 755] angle=4.6326 rad
    0x49B700B5,  // [ 756] angle=4.6388 rad
    0x49B700B5,  // [ 757] angle=4.6449 rad
    0x49B700B5,  // [ 758] angle=4.6510 rad
    0x49B700B5,  // [ 759] angle=4.6572 rad
    0x49B700B5,  // [ 760] angle=4.6633 rad
    0x49B700B5,  // [ 761] angle=4.6694 rad
    0x49B700B5,  // [ 762] angle=4.6756 rad
    0x49B700B5,  // [ 763] angle=4.6817 rad
    0x49B700B5,  // [ 764] angle=4.6878 rad
    0x49B700B5,  // [ 765] angle=4.6940 rad
    0x49B700B5,  // [ 766] angle=4.7001 rad
    0x49B700B5,  // [ 767] angle=4.7063 rad
    0x4D1500B5,  // [ 768] angle=4.7124 rad
    0x4D1500B5,  // [ 769] angle=4.7185 rad
    0x4D1500B5,  // [ 770] angle=4.7247 rad
    0x4D1500B5,  // [ 771] angle=4.7308 rad
    0x4D1500B5,  // [ 772] angle=4.7369 rad
    0x4D1500B5,  // [ 773] angle=4.7431 rad
    0x4D1500B5,  // [ 774] angle=4.7492 rad
    0x4D1500B5,  // [ 775] angle=4.7553 rad
    0x4D1500B5,  // [ 776] angle=4.7615 rad
    0x4D1500B5,  // [ 777] angle=4.7676 rad
    0x4D1500B5,  // [ 778] angle=4.7737 rad
    0x4D1500B5,  // [ 779] angle=4.7799 rad
    0x4D1500B5,  // [ 780] angle=4.7860 rad
    0x4D1500B5,  // [ 781] angle=4.7922 rad
    0x4D1500B5,  // [ 782] angle=4.7983 rad
    0x4D1500B5,  // [ 783] angle=4.8044 rad
    0x4D1500B5,  // [ 784] angle=4.8106 rad
    0x4D1500B5,  // [ 785] angle=4.8167 rad
    0x4D1500B5,  // [ 786] angle=4.8228 rad
    0x4D470091,  // [ 787] angle=4.8290 rad
    0x4D470091,  // [ 788] angle=4.8351 rad
    0x4D870071,  // [ 789] angle=4.8412 rad
    0x4D870071,  // [ 790] angle=4.8474 rad
    0x4D870071,  // [ 791] angle=4.8535 rad
    0x4DDB0055,  // [ 792] angle=4.8597 rad
    0x4DDB0055,  // [ 793] angle=4.8658 rad
    0x4DDB0055,  // [ 794] angle=4.8719 rad
    0x4E0F0091,  // [ 795] angle=4.8781 rad
    0x4E0F0091,  // [ 796] angle=4.8842 rad
    0x4E4D003D,  // [ 797] angle=4.8903 rad
    0x4E4D003D,  // [ 798] angle=4.8965 rad
    0x4E4D003D,  // [ 799] angle=4.9026 rad
    0x4E960065,  // [ 800] angle=4.9087 rad
    0x4E960065,  // [ 801] angle=4.9149 rad
    0x4E960065,  // [ 802] angle=4.9210 rad
    0x4EF00029,  // [ 803] angle=4.9271 rad
    0x4EF00029,  // [ 804] angle=4.9333 rad
    0x4EF00029,  // [ 805] angle=4.9394 rad
    0x4EF00029,  // [ 806] angle=4.9456 rad
    0x4F610041,  // [ 807] angle=4.9517 rad
    0x4F610041,  // [ 808] angle=4.9578 rad
    0x4F610041,  // [ 809] angle=4.9640 rad
    0x4F610041,  // [ 810] angle=4.9701 rad
    0x4F610041,  // [ 811] angle=4.9762 rad
    0x4FF00019,  // [ 812] angle=4.9824 rad
    0x4FF00019,  // [ 813] angle=4.9885 rad
    0x4FF00019,  // [ 814] angle=4.9946 rad
    0x4FF00019,  // [ 815] angle=5.0008 rad
    0x4FF00019,  // [ 816] angle=5.0069 rad
    0x4FF00019,  // [ 817] angle=5.0130 rad
    0x4FF00019,  // [ 818] angle=5.0192 rad
    0x50AF0025,  // [ 819] angle=5.0253 rad
    0x50AF0025,  // [ 820] angle=5.0315 rad
    0x50AF0025,  // [ 821] angle=5.0376 rad
    0x50AF0025,  // [ 822] angle=5.0437 rad
    0x50AF0025,  // [ 823] angle=5.0499 rad
    0x50AF0025,  // [ 824] angle=5.0560 rad
    0x50AF0025,  // [ 825] angle=5.0621 rad
    0x50AF0025,  // [ 826] angle=5.0683 rad
    0x50AF0025,  // [ 827] angle=5.0744 rad
    0x51B7000D,  // [ 828] angle=5.0805 rad
    0x51B7000D,  // [ 829] angle=5.0867 rad
    0x51B7000D,  // [ 830] angle=5.0928 rad
    0x51B7000D,  // [ 831] angle=5.0990 rad
    0x51B7000D,  // [ 832] angle=5.1051 rad
    0x51B7000D,  // [ 833] angle=5.1112 rad
    0x51B7000D,  // [ 834] angle=5.1174 rad
    0x51B7000D,  // [ 835] angle=5.1235 rad
    0x52650055,  // [ 836] angle=5.1296 rad
    0x52650055,  // [ 837] angle=5.1358 rad
    0x52650055,  // [ 838] angle=5.1419 rad
    0x52650055,  // [ 839] angle=5.1480 rad
    0x52650055,  // [ 840] angle=5.1542 rad
    0x52A80059,  // [ 841] angle=5.1603 rad
    0x52A80059,  // [ 842] angle=5.1664 rad
    0x52A80059,  // [ 843] angle=5.1726 rad
    0x52A80059,  // [ 844] angle=5.1787 rad
    0x533D0011,  // [ 845] angle=5.1849 rad
    0x533D0011,  // [ 846] angle=5.1910 rad
    0x533D0011,  // [ 847] angle=5.1971 rad
    0x533D0011,  // [ 848] angle=5.2033 rad
    0x533D0011,  // [ 849] angle=5.2094 rad
    0x533D0011,  // [ 850] angle=5.2155 rad
    0x533D0011,  // [ 851] angle=5.2217 rad
    0x53EB0041,  // [ 852] angle=5.2278 rad
    0x53EB0041,  // [ 853] angle=5.2339 rad
    0x53EB0041,  // [ 854] angle=5.2401 rad
    0x53EB0041,  // [ 855] angle=5.2462 rad
    0x53EB0041,  // [ 856] angle=5.2524 rad
    0x544E0035,  // [ 857] angle=5.2585 rad
    0x544E0035,  // [ 858] angle=5.2646 rad
    0x544E0035,  // [ 859] angle=5.2708 rad
    0x544E0035,  // [ 860] angle=5.2769 rad
    0x54BA006D,  // [ 861] angle=5.2830 rad
    0x54BA006D,  // [ 862] angle=5.2892 rad
    0x54BA006D,  // [ 863] angle=5.2953 rad
    0x54BA006D,  // [ 864] angle=5.3014 rad
    0x54BA006D,  // [ 865] angle=5.3076 rad
    0x54BA006D,  // [ 866] angle=5.3137 rad
    0x54BA006D,  // [ 867] angle=5.3198 rad
    0x55B20005,  // [ 868] angle=5.3260 rad
    0x55B20005,  // [ 869] angle=5.3321 rad
    0x55B20005,  // [ 870] angle=5.3383 rad
    0x55B20005,  // [ 871] angle=5.3444 rad
    0x55B20005,  // [ 872] angle=5.3505 rad
    0x55B20005,  // [ 873] angle=5.3567 rad
    0x55B20005,  // [ 874] angle=5.3628 rad
    0x55B20005,  // [ 875] angle=5.3689 rad
    0x55B20005,  // [ 876] angle=5.3751 rad
    0x55B20005,  // [ 877] angle=5.3812 rad
    0x55B20005,  // [ 878] angle=5.3873 rad
    0x56E10049,  // [ 879] angle=5.3935 rad
    0x56E10049,  // [ 880] angle=5.3996 rad
    0x56E10049,  // [ 881] angle=5.4057 rad
    0x56E10049,  // [ 882] angle=5.4119 rad
    0x56E10049,  // [ 883] angle=5.4180 rad
    0x56E10049,  // [ 884] angle=5.4242 rad
    0x56E10049,  // [ 885] angle=5.4303 rad
    0x56E10049,  // [ 886] angle=5.4364 rad
    0x57260061,  // [ 887] angle=5.4426 rad
    0x57260061,  // [ 888] angle=5.4487 rad
    0x57260061,  // [ 889] angle=5.4548 rad
    0x5793001D,  // [ 890] angle=5.4610 rad
    0x5793001D,  // [ 891] angle=5.4671 rad
    0x5793001D,  // [ 892] angle=5.4732 rad
    0x5793001D,  // [ 893] angle=5.4794 rad
    0x5793001D,  // [ 894] angle=5.4855 rad
    0x5793001D,  // [ 895] angle=5.4917 rad
    0x585B001D,  // [ 896] angle=5.4978 rad
    0x585B001D,  // [ 897] angle=5.5039 rad
    0x585B001D,  // [ 898] angle=5.5101 rad
    0x585B001D,  // [ 899] angle=5.5162 rad
    0x585B001D,  // [ 900] angle=5.5223 rad
    0x585B001D,  // [ 901] angle=5.5285 rad
    0x585B001D,  // [ 902] angle=5.5346 rad
    0x58C80061,  // [ 903] angle=5.5407 rad
    0x58C80061,  // [ 904] angle=5.5469 rad
    0x58C80061,  // [ 905] angle=5.5530 rad
    0x590D0049,  // [ 906] angle=5.5591 rad
    0x590D0049,  // [ 907] angle=5.5653 rad
    0x590D0049,  // [ 908] angle=5.5714 rad
    0x590D0049,  // [ 909] angle=5.5776 rad
    0x590D0049,  // [ 910] angle=5.5837 rad
    0x590D0049,  // [ 911] angle=5.5898 rad
    0x590D0049,  // [ 912] angle=5.5960 rad
    0x590D0049,  // [ 913] angle=5.6021 rad
    0x5A3C0005,  // [ 914] angle=5.6082 rad
    0x5A3C0005,  // [ 915] angle=5.6144 rad
    0x5A3C0005,  // [ 916] angle=5.6205 rad
    0x5A3C0005,  // [ 917] angle=5.6266 rad
    0x5A3C0005,  // [ 918] angle=5.6328 rad
    0x5A3C0005,  // [ 919] angle=5.6389 rad
    0x5A3C0005,  // [ 920] angle=5.6450 rad
    0x5A3C0005,  // [ 921] angle=5.6512 rad
    0x5A3C0005,  // [ 922] angle=5.6573 rad
    0x5A3C0005,  // [ 923] angle=5.6635 rad
    0x5A3C0005,  // [ 924] angle=5.6696 rad
    0x5B34006D,  // [ 925] angle=5.6757 rad
    0x5B34006D,  // [ 926] angle=5.6819 rad
    0x5B34006D,  // [ 927] angle=5.6880 rad
    0x5B34006D,  // [ 928] angle=5.6941 rad
    0x5B34006D,  // [ 929] angle=5.7003 rad
    0x5B34006D,  // [ 930] angle=5.7064 rad
    0x5B34006D,  // [ 931] angle=5.7125 rad
    0x5BA00035,  // [ 932] angle=5.7187 rad
    0x5BA00035,  // [ 933] angle=5.7248 rad
    0x5BA00035,  // [ 934] angle=5.7310 rad
    0x5BA00035,  // [ 935] angle=5.7371 rad
    0x5C030041,  // [ 936] angle=5.7432 rad
    0x5C030041,  // [ 937] angle=5.7494 rad
    0x5C030041,  // [ 938] angle=5.7555 rad
    0x5C030041,  // [ 939] angle=5.7616 rad
    0x5C030041,  // [ 940] angle=5.7678 rad
    0x5CB10011,  // [ 941] angle=5.7739 rad
    0x5CB10011,  // [ 942] angle=5.7800 rad
    0x5CB10011,  // [ 943] angle=5.7862 rad
    0x5CB10011,  // [ 944] angle=5.7923 rad
    0x5CB10011,  // [ 945] angle=5.7984 rad
    0x5CB10011,  // [ 946] angle=5.8046 rad
    0x5CB10011,  // [ 947] angle=5.8107 rad
    0x5D460059,  // [ 948] angle=5.8169 rad
    0x5D460059,  // [ 949] angle=5.8230 rad
    0x5D460059,  // [ 950] angle=5.8291 rad
    0x5D460059,  // [ 951] angle=5.8353 rad
    0x5D890055,  // [ 952] angle=5.8414 rad
    0x5D890055,  // [ 953] angle=5.8475 rad
    0x5D890055,  // [ 954] angle=5.8537 rad
    0x5D890055,  // [ 955] angle=5.8598 rad
    0x5D890055,  // [ 956] angle=5.8659 rad
    0x5E37000D,  // [ 957] angle=5.8721 rad
    0x5E37000D,  // [ 958] angle=5.8782 rad
    0x5E37000D,  // [ 959] angle=5.8844 rad
    0x5E37000D,  // [ 960] angle=5.8905 rad
    0x5E37000D,  // [ 961] angle=5.8966 rad
    0x5E37000D,  // [ 962] angle=5.9028 rad
    0x5E37000D,  // [ 963] angle=5.9089 rad
    0x5E37000D,  // [ 964] angle=5.9150 rad
    0x5F3F0025,  // [ 965] angle=5.9212 rad
    0x5F3F0025,  // [ 966] angle=5.9273 rad
    0x5F3F0025,  // [ 967] angle=5.9334 rad
    0x5F3F0025,  // [ 968] angle=5.9396 rad
    0x5F3F0025,  // [ 969] angle=5.9457 rad
    0x5F3F0025,  // [ 970] angle=5.9518 rad
    0x5F3F0025,  // [ 971] angle=5.9580 rad
    0x5F3F0025,  // [ 972] angle=5.9641 rad
    0x5F3F0025,  // [ 973] angle=5.9703 rad
    0x5FFE0019,  // [ 974] angle=5.9764 rad
    0x5FFE0019,  // [ 975] angle=5.9825 rad
    0x5FFE0019,  // [ 976] angle=5.9887 rad
    0x5FFE0019,  // [ 977] angle=5.9948 rad
    0x5FFE0019,  // [ 978] angle=6.0009 rad
    0x5FFE0019,  // [ 979] angle=6.0071 rad
    0x5FFE0019,  // [ 980] angle=6.0132 rad
    0x608D0041,  // [ 981] angle=6.0193 rad
    0x608D0041,  // [ 982] angle=6.0255 rad
    0x608D0041,  // [ 983] angle=6.0316 rad
    0x608D0041,  // [ 984] angle=6.0377 rad
    0x608D0041,  // [ 985] angle=6.0439 rad
    0x60FD0029,  // [ 986] angle=6.0500 rad
    0x60FD0029,  // [ 987] angle=6.0562 rad
    0x60FD0029,  // [ 988] angle=6.0623 rad
    0x60FD0029,  // [ 989] angle=6.0684 rad
    0x61570065,  // [ 990] angle=6.0746 rad
    0x61570065,  // [ 991] angle=6.0807 rad
    0x61570065,  // [ 992] angle=6.0868 rad
    0x61A1003D,  // [ 993] angle=6.0930 rad
    0x61A1003D,  // [ 994] angle=6.0991 rad
    0x61A1003D,  // [ 995] angle=6.1052 rad
    0x61DF0091,  // [ 996] angle=6.1114 rad
    0x61DF0091,  // [ 997] angle=6.1175 rad
    0x62130055,  // [ 998] angle=6.1237 rad
    0x62130055,  // [ 999] angle=6.1298 rad
    0x62130055,  // [1000] angle=6.1359 rad
    0x62670071,  // [1001] angle=6.1421 rad
    0x62670071,  // [1002] angle=6.1482 rad
    0x62670071,  // [1003] angle=6.1543 rad
    0x62A70091,  // [1004] angle=6.1605 rad
    0x62A70091,  // [1005] angle=6.1666 rad
    0x62D900B5,  // [1006] angle=6.1727 rad
    0x62D900B5,  // [1007] angle=6.1789 rad
    0x62D900B5,  // [1008] angle=6.1850 rad
    0x62D900B5,  // [1009] angle=6.1911 rad
    0x62D900B5,  // [1010] angle=6.1973 rad
    0x62D900B5,  // [1011] angle=6.2034 rad
    0x62D900B5,  // [1012] angle=6.2096 rad
    0x62D900B5,  // [1013] angle=6.2157 rad
    0x62D900B5,  // [1014] angle=6.2218 rad
    0x62D900B5,  // [1015] angle=6.2280 rad
    0x62D900B5,  // [1016] angle=6.2341 rad
    0x62D900B5,  // [1017] angle=6.2402 rad
    0x62D900B5,  // [1018] angle=6.2464 rad
    0x62D900B5,  // [1019] angle=6.2525 rad
    0x62D900B5,  // [1020] angle=6.2586 rad
    0x62D900B5,  // [1021] angle=6.2648 rad
    0x62D900B5,  // [1022] angle=6.2709 rad
    0x62D900B5  // [1023] angle=6.2770 rad
};

// Margin table: angular distance to nearest triple (Q4.12)
static const uint16_t snap_margin[SNAP_LUT_SIZE] = {
    0xEC2B,
    0x5A0B,
    0xC7EB,
    0x35CC,
    0xA3AC,
    0x118C,
    0x7F6D,
    0xED4D,
    0x5B2D,
    0xC90D,
    0x36EE,
    0xA4CE,
    0x12AE,
    0x808F,
    0xEE6F,
    0x5C4F,
    0xCA2F,
    0x3810,
    0x5A10,
    0x3CE4,
    0x553C,
    0x189F,
    0x7981,
    0x0BA0,
    0x9BAC,
    0x098D,
    0x8893,
    0x2825,
    0x69FB,
    0xDD61,
    0xB4BE,
    0x46DE,
    0xC3CE,
    0xCE51,
    0x6071,
    0xADBA,
    0x1B9B,
    0x7685,
    0x08A5,
    0x68A1,
    0xD681,
    0xBB9F,
    0x4DBF,
    0xDFDE,
    0x8948,
    0xF728,
    0x6508,
    0x2D17,
    0xBF37,
    0x5157,
    0xE376,
    0x720D,
    0xDFED,
    0x4DCE,
    0x4452,
    0xD672,
    0x6892,
    0xFAB1,
    0x8CD1,
    0x1EF1,
    0xD199,
    0x3F7A,
    0xAD5A,
    0x1B3A,
    0x891B,
    0x0905,
    0x9B25,
    0x2D45,
    0x24F4,
    0x92D4,
    0x00B5,
    0x6E95,
    0x238B,
    0x73F0,
    0x1E30,
    0xB050,
    0x426F,
    0x7A4E,
    0xE82F,
    0x560F,
    0x3C11,
    0xCE30,
    0x6050,
    0xF270,
    0x5FC9,
    0xCDA9,
    0x3B89,
    0x5696,
    0xE8B6,
    0xB045,
    0x1E25,
    0x73FA,
    0x061A,
    0x244E,
    0x922F,
    0x000F,
    0x9211,
    0x2430,
    0xB650,
    0x4870,
    0xA81A,
    0x15FB,
    0x83DB,
    0xF1BB,
    0x5F9B,
    0x3284,
    0xC4A4,
    0x56C4,
    0xE8E3,
    0x7B03,
    0x0D23,
    0x550A,
    0xC2EB,
    0x30CB,
    0x9EAB,
    0x0C8C,
    0x7A6C,
    0x17B4,
    0xA9D3,
    0x1178,
    0x80A8,
    0x12C7,
    0x2E9F,
    0x9C7F,
    0x0A60,
    0x87C0,
    0x19E0,
    0xAC00,
    0x3E1F,
    0xAC00,
    0x19E0,
    0x87C0,
    0x0A60,
    0x9C7F,
    0x2E9F,
    0x12C7,
    0x80A8,
    0x1178,
    0xA9D3,
    0x17B4,
    0x7A6C,
    0x0C8C,
    0x9EAB,
    0x30CB,
    0xC2EB,
    0x550A,
    0x0D23,
    0x7B03,
    0xE8E3,
    0x56C4,
    0xC4A4,
    0x3284,
    0x5F9B,
    0xF1BB,
    0x83DB,
    0x15FB,
    0xA81A,
    0x4870,
    0xB650,
    0x2430,
    0x9211,
    0x000F,
    0x922F,
    0x244E,
    0x061A,
    0x73FA,
    0x1E25,
    0xB045,
    0xE8B6,
    0x5696,
    0x3B89,
    0xCDA9,
    0x5FC9,
    0xF270,
    0x6050,
    0xCE30,
    0x3C11,
    0x560F,
    0xE82F,
    0x7A4E,
    0x426F,
    0xB050,
    0x1E30,
    0x73F0,
    0x238B,
    0x6E95,
    0x00B5,
    0x92D4,
    0x24F4,
    0x2D45,
    0x9B25,
    0x0905,
    0x891B,
    0x1B3A,
    0xAD5A,
    0x3F7A,
    0xD199,
    0x1EF1,
    0x8CD1,
    0xFAB1,
    0x6892,
    0xD672,
    0x4452,
    0x4DCE,
    0xDFED,
    0x720D,
    0xE376,
    0x5157,
    0xBF37,
    0x2D17,
    0x6508,
    0xF728,
    0x8948,
    0xDFDE,
    0x4DBF,
    0xBB9F,
    0xD681,
    0x68A1,
    0x08A5,
    0x7685,
    0x1B9B,
    0xADBA,
    0x6071,
    0xCE51,
    0xC3CE,
    0x46DE,
    0xB4BE,
    0xDD61,
    0x69FB,
    0x2825,
    0x8893,
    0x098D,
    0x9BAC,
    0x0BA0,
    0x7981,
    0x189F,
    0x553C,
    0x3CE4,
    0x5A10,
    0x3810,
    0xCA2F,
    0x5C4F,
    0xEE6F,
    0x808F,
    0x12AE,
    0xA4CE,
    0x36EE,
    0xC90D,
    0x5B2D,
    0xED4D,
    0x7F6D,
    0x118C,
    0xA3AC,
    0x35CC,
    0xC7EB,
    0x5A0B,
    0xEC2B,
    0x5A0B,
    0xC7EB,
    0x35CC,
    0xA3AC,
    0x118C,
    0x7F6D,
    0xED4D,
    0x5B2D,
    0xC90D,
    0x36EE,
    0xA4CE,
    0x12AE,
    0x808F,
    0xEE6F,
    0x5C4F,
    0xCA2F,
    0x3810,
    0x5A10,
    0x3CE4,
    0x553C,
    0x189F,
    0x7981,
    0x0BA0,
    0x9BAC,
    0x098D,
    0x8893,
    0x2825,
    0x69FB,
    0xDD61,
    0xB4BE,
    0x46DE,
    0xC3CE,
    0xCE51,
    0x6071,
    0xADBA,
    0x1B9B,
    0x7685,
    0x08A5,
    0x68A1,
    0xD681,
    0xBB9F,
    0x4DBF,
    0xDFDE,
    0x8948,
    0xF728,
    0x6508,
    0x2D17,
    0xBF37,
    0x5157,
    0xE376,
    0x720D,
    0xDFED,
    0x4DCE,
    0x4452,
    0xD672,
    0x6892,
    0xFAB1,
    0x8CD1,
    0x1EF1,
    0xD199,
    0x3F7A,
    0xAD5A,
    0x1B3A,
    0x891B,
    0x0905,
    0x9B25,
    0x2D45,
    0x24F4,
    0x92D4,
    0x00B5,
    0x6E95,
    0x238B,
    0x73F0,
    0x1E30,
    0xB050,
    0x426F,
    0x7A4E,
    0xE82F,
    0x560F,
    0x3C11,
    0xCE30,
    0x6050,
    0xF270,
    0x5FC9,
    0xCDA9,
    0x3B89,
    0x5696,
    0xE8B6,
    0xB045,
    0x1E25,
    0x73FA,
    0x061A,
    0x244E,
    0x922F,
    0x000F,
    0x9211,
    0x2430,
    0xB650,
    0x4870,
    0xA81A,
    0x15FB,
    0x83DB,
    0xF1BB,
    0x5F9B,
    0x3284,
    0xC4A4,
    0x56C4,
    0xE8E3,
    0x7B03,
    0x0D23,
    0x550A,
    0xC2EB,
    0x30CB,
    0x9EAB,
    0x0C8C,
    0x7A6C,
    0x17B4,
    0xA9D3,
    0x1178,
    0x80A8,
    0x12C7,
    0x2E9F,
    0x9C7F,
    0x0A60,
    0x87C0,
    0x19E0,
    0xAC00,
    0x3E1F,
    0xAC00,
    0x19E0,
    0x87C0,
    0x0A60,
    0x9C7F,
    0x2E9F,
    0x12C7,
    0x80A8,
    0x1178,
    0xA9D3,
    0x17B4,
    0x7A6C,
    0x0C8C,
    0x9EAB,
    0x30CB,
    0xC2EB,
    0x550A,
    0x0D23,
    0x7B03,
    0xE8E3,
    0x56C4,
    0xC4A4,
    0x3284,
    0x5F9B,
    0xF1BB,
    0x83DB,
    0x15FB,
    0xA81A,
    0x4870,
    0xB650,
    0x2430,
    0x9211,
    0x000F,
    0x922F,
    0x244E,
    0x061A,
    0x73FA,
    0x1E25,
    0xB045,
    0xE8B6,
    0x5696,
    0x3B89,
    0xCDA9,
    0x5FC9,
    0xF270,
    0x6050,
    0xCE30,
    0x3C11,
    0x560F,
    0xE82F,
    0x7A4E,
    0x426F,
    0xB050,
    0x1E30,
    0x73F0,
    0x238B,
    0x6E95,
    0x00B5,
    0x92D4,
    0x24F4,
    0x2D45,
    0x9B25,
    0x0905,
    0x891B,
    0x1B3A,
    0xAD5A,
    0x3F7A,
    0xD199,
    0x1EF1,
    0x8CD1,
    0xFAB1,
    0x6892,
    0xD672,
    0x4452,
    0x4DCE,
    0xDFED,
    0x720D,
    0xE376,
    0x5157,
    0xBF37,
    0x2D17,
    0x6508,
    0xF728,
    0x8948,
    0xDFDE,
    0x4DBF,
    0xBB9F,
    0xD681,
    0x68A1,
    0x08A5,
    0x7685,
    0x1B9B,
    0xADBA,
    0x6071,
    0xCE51,
    0xC3CE,
    0x46DE,
    0xB4BE,
    0xDD61,
    0x69FB,
    0x2825,
    0x8893,
    0x098D,
    0x9BAC,
    0x0BA0,
    0x7981,
    0x189F,
    0x553C,
    0x3CE4,
    0x5A10,
    0x3810,
    0xCA2F,
    0x5C4F,
    0xEE6F,
    0x808F,
    0x12AE,
    0xA4CE,
    0x36EE,
    0xC90D,
    0x5B2D,
    0xED4D,
    0x7F6D,
    0x118C,
    0xA3AC,
    0x35CC,
    0xC7EB,
    0x5A0B,
    0xEC2B,
    0x5A0B,
    0xC7EB,
    0x35CC,
    0xA3AC,
    0x118C,
    0x7F6D,
    0xED4D,
    0x5B2D,
    0xC90D,
    0x36EE,
    0xA4CE,
    0x12AE,
    0x808F,
    0xEE6F,
    0x5C4F,
    0xCA2F,
    0x3810,
    0x5A10,
    0x3CE4,
    0x553C,
    0x189F,
    0x7981,
    0x0BA0,
    0x9BAC,
    0x098D,
    0x8893,
    0x2825,
    0x69FB,
    0xDD61,
    0xB4BE,
    0x46DE,
    0xC3CE,
    0xCE51,
    0x6071,
    0xADBA,
    0x1B9B,
    0x7685,
    0x08A5,
    0x68A1,
    0xD681,
    0xBB9F,
    0x4DBF,
    0xDFDE,
    0x8948,
    0xF728,
    0x6508,
    0x2D17,
    0xBF37,
    0x5157,
    0xE376,
    0x720D,
    0xDFED,
    0x4DCE,
    0x4452,
    0xD672,
    0x6892,
    0xFAB1,
    0x8CD1,
    0x1EF1,
    0xD199,
    0x3F7A,
    0xAD5A,
    0x1B3A,
    0x891B,
    0x0905,
    0x9B25,
    0x2D45,
    0x24F4,
    0x92D4,
    0x00B5,
    0x6E95,
    0x238B,
    0x73F0,
    0x1E30,
    0xB050,
    0x426F,
    0x7A4E,
    0xE82F,
    0x560F,
    0x3C11,
    0xCE30,
    0x6050,
    0xF270,
    0x5FC9,
    0xCDA9,
    0x3B89,
    0x5696,
    0xE8B6,
    0xB045,
    0x1E25,
    0x73FA,
    0x061A,
    0x244E,
    0x922F,
    0x000F,
    0x9211,
    0x2430,
    0xB650,
    0x4870,
    0xA81A,
    0x15FB,
    0x83DB,
    0xF1BB,
    0x5F9B,
    0x3284,
    0xC4A4,
    0x56C4,
    0xE8E3,
    0x7B03,
    0x0D23,
    0x550A,
    0xC2EB,
    0x30CB,
    0x9EAB,
    0x0C8C,
    0x7A6C,
    0x17B4,
    0xA9D3,
    0x1178,
    0x80A8,
    0x12C7,
    0x2E9F,
    0x9C7F,
    0x0A60,
    0x87C0,
    0x19E0,
    0xAC00,
    0x3E1F,
    0xAC00,
    0x19E0,
    0x87C0,
    0x0A60,
    0x9C7F,
    0x2E9F,
    0x12C7,
    0x80A8,
    0x1178,
    0xA9D3,
    0x17B4,
    0x7A6C,
    0x0C8C,
    0x9EAB,
    0x30CB,
    0xC2EB,
    0x550A,
    0x0D23,
    0x7B03,
    0xE8E3,
    0x56C4,
    0xC4A4,
    0x3284,
    0x5F9B,
    0xF1BB,
    0x83DB,
    0x15FB,
    0xA81A,
    0x4870,
    0xB650,
    0x2430,
    0x9211,
    0x000F,
    0x922F,
    0x244E,
    0x061A,
    0x73FA,
    0x1E25,
    0xB045,
    0xE8B6,
    0x5696,
    0x3B89,
    0xCDA9,
    0x5FC9,
    0xF270,
    0x6050,
    0xCE30,
    0x3C11,
    0x560F,
    0xE82F,
    0x7A4E,
    0x426F,
    0xB050,
    0x1E30,
    0x73F0,
    0x238B,
    0x6E95,
    0x00B5,
    0x92D4,
    0x24F4,
    0x2D45,
    0x9B25,
    0x0905,
    0x891B,
    0x1B3A,
    0xAD5A,
    0x3F7A,
    0xD199,
    0x1EF1,
    0x8CD1,
    0xFAB1,
    0x6892,
    0xD672,
    0x4452,
    0x4DCE,
    0xDFED,
    0x720D,
    0xE376,
    0x5157,
    0xBF37,
    0x2D17,
    0x6508,
    0xF728,
    0x8948,
    0xDFDE,
    0x4DBF,
    0xBB9F,
    0xD681,
    0x68A1,
    0x08A5,
    0x7685,
    0x1B9B,
    0xADBA,
    0x6071,
    0xCE51,
    0xC3CE,
    0x46DE,
    0xB4BE,
    0xDD61,
    0x69FB,
    0x2825,
    0x8893,
    0x098D,
    0x9BAC,
    0x0BA0,
    0x7981,
    0x189F,
    0x553C,
    0x3CE4,
    0x5A10,
    0x3810,
    0xCA2F,
    0x5C4F,
    0xEE6F,
    0x808F,
    0x12AE,
    0xA4CE,
    0x36EE,
    0xC90D,
    0x5B2D,
    0xED4D,
    0x7F6D,
    0x118C,
    0xA3AC,
    0x35CC,
    0xC7EB,
    0x5A0B,
    0xEC2B,
    0x5A0B,
    0xC7EB,
    0x35CC,
    0xA3AC,
    0x118C,
    0x7F6D,
    0xED4D,
    0x5B2D,
    0xC90D,
    0x36EE,
    0xA4CE,
    0x12AE,
    0x808F,
    0xEE6F,
    0x5C4F,
    0xCA2F,
    0x3810,
    0x5A10,
    0x3CE4,
    0x553C,
    0x189F,
    0x7981,
    0x0BA0,
    0x9BAC,
    0x098D,
    0x8893,
    0x2825,
    0x69FB,
    0xDD61,
    0xB4BE,
    0x46DE,
    0xC3CE,
    0xCE51,
    0x6071,
    0xADBA,
    0x1B9B,
    0x7685,
    0x08A5,
    0x68A1,
    0xD681,
    0xBB9F,
    0x4DBF,
    0xDFDE,
    0x8948,
    0xF728,
    0x6508,
    0x2D17,
    0xBF37,
    0x5157,
    0xE376,
    0x720D,
    0xDFED,
    0x4DCE,
    0x4452,
    0xD672,
    0x6892,
    0xFAB1,
    0x8CD1,
    0x1EF1,
    0xD199,
    0x3F7A,
    0xAD5A,
    0x1B3A,
    0x891B,
    0x0905,
    0x9B25,
    0x2D45,
    0x24F4,
    0x92D4,
    0x00B5,
    0x6E95,
    0x238B,
    0x73F0,
    0x1E30,
    0xB050,
    0x426F,
    0x7A4E,
    0xE82F,
    0x560F,
    0x3C11,
    0xCE30,
    0x6050,
    0xF270,
    0x5FC9,
    0xCDA9,
    0x3B89,
    0x5696,
    0xE8B6,
    0xB045,
    0x1E25,
    0x73FA,
    0x061A,
    0x244E,
    0x922F,
    0x000F,
    0x9211,
    0x2430,
    0xB650,
    0x4870,
    0xA81A,
    0x15FB,
    0x83DB,
    0xF1BB,
    0x5F9B,
    0x3284,
    0xC4A4,
    0x56C4,
    0xE8E3,
    0x7B03,
    0x0D23,
    0x550A,
    0xC2EB,
    0x30CB,
    0x9EAB,
    0x0C8C,
    0x7A6C,
    0x17B4,
    0xA9D3,
    0x1178,
    0x80A8,
    0x12C7,
    0x2E9F,
    0x9C7F,
    0x0A60,
    0x87C0,
    0x19E0,
    0xAC00,
    0x3E1F,
    0xAC00,
    0x19E0,
    0x87C0,
    0x0A60,
    0x9C7F,
    0x2E9F,
    0x12C7,
    0x80A8,
    0x1178,
    0xA9D3,
    0x17B4,
    0x7A6C,
    0x0C8C,
    0x9EAB,
    0x30CB,
    0xC2EB,
    0x550A,
    0x0D23,
    0x7B03,
    0xE8E3,
    0x56C4,
    0xC4A4,
    0x3284,
    0x5F9B,
    0xF1BB,
    0x83DB,
    0x15FB,
    0xA81A,
    0x4870,
    0xB650,
    0x2430,
    0x9211,
    0x000F,
    0x922F,
    0x244E,
    0x061A,
    0x73FA,
    0x1E25,
    0xB045,
    0xE8B6,
    0x5696,
    0x3B89,
    0xCDA9,
    0x5FC9,
    0xF270,
    0x6050,
    0xCE30,
    0x3C11,
    0x560F,
    0xE82F,
    0x7A4E,
    0x426F,
    0xB050,
    0x1E30,
    0x73F0,
    0x238B,
    0x6E95,
    0x00B5,
    0x92D4,
    0x24F4,
    0x2D45,
    0x9B25,
    0x0905,
    0x891B,
    0x1B3A,
    0xAD5A,
    0x3F7A,
    0xD199,
    0x1EF1,
    0x8CD1,
    0xFAB1,
    0x6892,
    0xD672,
    0x4452,
    0x4DCE,
    0xDFED,
    0x720D,
    0xE376,
    0x5157,
    0xBF37,
    0x2D17,
    0x6508,
    0xF728,
    0x8948,
    0xDFDE,
    0x4DBF,
    0xBB9F,
    0xD681,
    0x68A1,
    0x08A5,
    0x7685,
    0x1B9B,
    0xADBA,
    0x6071,
    0xCE51,
    0xC3CE,
    0x46DE,
    0xB4BE,
    0xDD61,
    0x69FB,
    0x2825,
    0x8893,
    0x098D,
    0x9BAC,
    0x0BA0,
    0x7981,
    0x189F,
    0x553C,
    0x3CE4,
    0x5A10,
    0x3810,
    0xCA2F,
    0x5C4F,
    0xEE6F,
    0x808F,
    0x12AE,
    0xA4CE,
    0x36EE,
    0xC90D,
    0x5B2D,
    0xED4D,
    0x7F6D,
    0x118C,
    0xA3AC,
    0x35CC,
    0xC7EB,
    0x5A0B
};

#endif // SNAP_LUT_H
